### PR TITLE
convert project wiki to markdown documentation [ci-skip]

### PR DESCRIPTION
**Pull request by Grabsky**
Let me know if there is anything else that could be added, and of course, I'll be more than happy to tweak it to your liking.

I can also add addon docs in the future, but I think these should be kept separately.

### CODE REVIEW

**Comment by Grabsky** [comment]
Markdown-parsed file can be viewed here:
https://github.com/LuaLink/LuaLink/blob/e77e3b792fac3e0a24e17ed244cc015540f50d6a/README.md

**Comment by Saturn745** [comment]
There is some basic "docs" on the [Wiki](https://github.com/LuaLink/LuaLink/wiki) but last I checked there wasn't an easy way to contribute to the wiki pages. Perhaps we should move the docs to it's own Markdown file and merge this one and the wiki page?

**Comment by Grabsky** [comment]
I should be able to contribute to wiki just fine. Just didn't know about it's existence until now.

I'll try to merge this effort with the existing documentation on the wiki, and convert the whole **Documentation** section introduced by this PR to instead link to the proper wiki. Maybe some key information like luaj/luakt reference should be kept too.

I think it's nicer than maintaining a bunch of markdown files in the main repository.

**Comment by Saturn745** [comment]
> I should be able to contribute to wiki just fine. Just didn't know about it's existence until now.
> 
> I'll try to merge this effort with the existing documentation, and convert the whole **Documentation** section introduced by this PR to instead link to the proper wiki. Maybe some key information like luaj/luakt reference should be kept too.
> 
> I think it's nicer than maintaining a bunch of markdown files in the main repository.

If you would like to try and contribute to the wiki page feel free to. I believe the last time I looked there's no proper way to PR to a wiki page and I will have to manually copy your version over.

**Comment by Grabsky** [comment]
Searched a bit and you're correct, there is still no way to submit a "proper" pull request to the wiki itself.

At this point, I think having a `docs` directory in the repo is not as bad as I initially thought. I have seen people do that in the past, now I know why. It's should actually be more convinient for both maintainers and contributors.

If you don't mind, I should be able to migrate the wiki over to be stored within the project files (as you initially suggested) and restructure it a bit so it "reads" nicely.

**Comment by Saturn745** [comment]
> Searched a bit and you're correct, there is still no way to submit a "proper" pull request to the wiki itself.
> 
> At this point, I think having a `docs` directory in the repo is not as bad as I initially thought. I have seen people do that in the past, now I know why. It should actually be more convinient for both maintainers and contributors.
> 
> If you don't mind, I can migrate the wiki over to be stored within the project files (as you initially suggested) and restructure it a bit so it "reads" nicely.

If you want to do it go right ahead.

**Comment by Grabsky** [comment]
Converted PR to draft and "rebased" existing wiki on top of it. Some spelling/grammar issues are likely to be present, but it shouldn't be too bad as I spent some time fixing them.

Let me know what you think about the layout.

Some information may be missing but I think it's done for the most part, keep me informed what else you want me to include.

**Comment by Saturn745** [comment]
Wow it looks great

**Comment by Grabsky** [comment]
Thanks for the kind words, I pushed update to the navigation tree to make it work (and look) better.

**Comment by Saturn745** [comment]
> Thanks for the kind words, I pushed update to the navigation tree to make it work (and look) better.

I like it a lot. Thank you!

**Comment by Grabsky** [comment]
I think everything is covered now, marking as ready-for-review. Perhaps it's also a good idea to open GitHub Discussions as a place for other people to seek help.

Addons documentation remains incomplete as I'm not too familar with that system yet.

**Comment by Saturn745** [comment]
> I think everything is covered now, marking as ready-for-review. Perhaps it's also a good idea to open GitHub Discussions as a place for other people to seek help.

Yes I can open up GitHub discussions. Don't worry about the addon system for now. Just mark it ready whenever you feel that it's done and I'll merge

**Comment by Saturn745** [comment]
Updated the Wiki to link to the new docs https://github.com/LuaLink/LuaLink/wiki

Really appreciate you for doing this.

**Pull request merged**
